# Generated by Django 6.1 on 2026-10-02 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='margen_ganancia_pct',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de ganancia que se suma al costo. Ej: 30 = 30%.', max_digits=5),
        ),
        migrations.AddField(
            model_name='empresa',
            name='precio_transporte_km',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Precio por kilometro de transporte (CLP).', max_digits=10),
        ),
    ]
