# Generated by Django 6.1 on 2026-10-02 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_cotizacion_costo_transporte_and_more'),
        ('users', '0002_empresa_margen_ganancia_pct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_produccion', models.CharField(choices=[('POR_INICIAR', 'Por iniciar'), ('EN_FABRICACION', 'En fabricacion'), ('TERMINADO', 'Terminado'), ('ENTREGADO', 'Entregado')], default='POR_INICIAR', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='core.cliente')),
                ('cotizacion', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='proyecto', to='core.cotizacion')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='users.empresa')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
