# Generated by Django 6.1 on 2026-10-01 04:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20)),
                ('direccion_entrega', models.CharField(blank=True, max_length=255)),
                ('requiere_transporte', models.BooleanField(default=False)),
                ('distancia_transporte_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('comentarios', models.TextField(blank=True)),
                ('monto_agregado', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='core.cliente')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='users.empresa')),
                ('resuelta_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_resueltas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cotizacion',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='VentanaCotizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Linea20', 'Corredera (Linea 20)'), ('Linea25simple', 'Corredera (Linea 25 simple)'), ('Linea25lluvia', 'Corredera lluvia (Linea 25)'), ('Linea42f', 'Fijo (Linea 42)'), ('Linea42p', 'Proyeccion (Linea 42)')], max_length=20)),
                ('color', models.CharField(choices=[('BRONCE', 'Bronce (Negro)'), ('MATE', 'Mate (Blanco)'), ('ALUMINIO', 'Aluminio (Gris)'), ('TITANEO', 'Titaneo'), ('MADERA', 'Madera (Cafe)')], max_length=20)),
                ('vidrio', models.CharField(choices=[('BRONCE_4', 'Bronce 4mm'), ('BRONCE_5', 'Bronce 5mm'), ('INCOLORO_4', 'Incoloro 4mm'), ('INCOLORO_5', 'Incoloro 5mm'), ('SOLARCOOL_4', 'SolarCool 4mm'), ('SOLARCOOL_5', 'SolarCool 5mm')], max_length=20)),
                ('ancho_cm', models.DecimalField(decimal_places=1, max_digits=7)),
                ('alto_cm', models.DecimalField(decimal_places=1, max_digits=7)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventanas', to='core.cotizacion')),
            ],
            options={
                'verbose_name': 'Ventana cotizada',
                'verbose_name_plural': 'Ventanas cotizadas',
            },
        ),
    ]
