# Generated by Django 6.1 on 2026-10-02 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cotizacion_ventanacotizada'),
        ('users', '0002_empresa_margen_ganancia_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='costo_transporte',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='ventanacotizada',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='ventanacotizada',
            name='precio_calculado',
            field=models.BooleanField(default=False, help_text='False si falto algun precio en el catalogo.'),
        ),
        migrations.AddField(
            model_name='ventanacotizada',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='PerfilIndividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ej: RIEL_INF_SIMPLE.', max_length=30)),
                ('nombre', models.CharField(max_length=80)),
                ('largo_tira_m', models.DecimalField(decimal_places=3, max_digits=6)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfiles_individuales', to='users.empresa')),
            ],
            options={
                'verbose_name': 'Perfil individual',
                'verbose_name_plural': 'Perfiles individuales',
                'ordering': ['codigo'],
                'unique_together': {('empresa', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='SerieAluminio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Identificador corto, p. ej. L20 o L25.', max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_aluminio', to='users.empresa')),
            ],
            options={
                'verbose_name': 'Serie de aluminio',
                'verbose_name_plural': 'Series de aluminio',
                'ordering': ['codigo'],
                'unique_together': {('empresa', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ej: FELPA, PESTILLO, BURLETE.', max_length=30)),
                ('nombre', models.CharField(max_length=80)),
                ('unidad', models.CharField(blank=True, help_text='Informativo: m, unidad, etc.', max_length=20)),
                ('precio_paquete', models.DecimalField(decimal_places=0, max_digits=12)),
                ('cantidad_paquete', models.DecimalField(decimal_places=3, help_text='Unidades o metros que trae el paquete/rollo.', max_digits=12)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='users.empresa')),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
                'ordering': ['codigo'],
                'unique_together': {('empresa', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='PlanchaVidrio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_vidrio', models.CharField(choices=[('BRONCE_4', 'Bronce 4mm'), ('BRONCE_5', 'Bronce 5mm'), ('INCOLORO_4', 'Incoloro 4mm'), ('INCOLORO_5', 'Incoloro 5mm'), ('SOLARCOOL_4', 'SolarCool 4mm'), ('SOLARCOOL_5', 'SolarCool 5mm')], max_length=20)),
                ('ancho_plancha_m', models.DecimalField(decimal_places=3, max_digits=5)),
                ('alto_plancha_m', models.DecimalField(decimal_places=3, max_digits=5)),
                ('precio', models.DecimalField(decimal_places=0, help_text='Precio de la plancha (CLP).', max_digits=12)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planchas_vidrio', to='users.empresa')),
            ],
            options={
                'verbose_name': 'Plancha de vidrio',
                'verbose_name_plural': 'Planchas de vidrio',
                'unique_together': {('empresa', 'tipo_vidrio')},
            },
        ),
        migrations.CreateModel(
            name='PrecioPerfilIndividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('BRONCE', 'Bronce (Negro)'), ('MATE', 'Mate (Blanco)'), ('ALUMINIO', 'Aluminio (Gris)'), ('TITANEO', 'Titaneo'), ('MADERA', 'Madera (Cafe)')], max_length=20)),
                ('precio', models.DecimalField(decimal_places=0, help_text='Precio de la tira (CLP).', max_digits=12)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='core.perfilindividual')),
            ],
            options={
                'verbose_name': 'Precio de perfil individual',
                'verbose_name_plural': 'Precios de perfil individual',
                'unique_together': {('perfil', 'color')},
            },
        ),
        migrations.CreateModel(
            name='PrecioSerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('BRONCE', 'Bronce (Negro)'), ('MATE', 'Mate (Blanco)'), ('ALUMINIO', 'Aluminio (Gris)'), ('TITANEO', 'Titaneo'), ('MADERA', 'Madera (Cafe)')], max_length=20)),
                ('precio', models.DecimalField(decimal_places=0, help_text='Precio del paquete completo (CLP).', max_digits=12)),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='core.seriealuminio')),
            ],
            options={
                'verbose_name': 'Precio de serie',
                'verbose_name_plural': 'Precios de serie',
                'unique_together': {('serie', 'color')},
            },
        ),
        migrations.CreateModel(
            name='PerfilSerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Debe coincidir con la hoja de corte (ej: Jamba).', max_length=60)),
                ('peso_kg', models.DecimalField(decimal_places=3, max_digits=7)),
                ('largo_tira_m', models.DecimalField(decimal_places=3, max_digits=6)),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfiles', to='core.seriealuminio')),
            ],
            options={
                'verbose_name': 'Perfil de serie',
                'verbose_name_plural': 'Perfiles de serie',
                'ordering': ['serie', 'nombre'],
                'unique_together': {('serie', 'nombre')},
            },
        ),
    ]
