# Generated by Django 6.1 on 2026-10-07 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cotizacion_costo_transporte_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilserie',
            options={'ordering': ['serie', 'orden', 'nombre'], 'verbose_name': 'Perfil de serie', 'verbose_name_plural': 'Perfiles de serie'},
        ),
        migrations.AddField(
            model_name='perfilserie',
            name='orden',
            field=models.PositiveSmallIntegerField(default=0, help_text='Orden de aparicion en listas y hoja de corte.'),
        ),
    ]
