# Generated by Django 6.1 on 2026-10-07 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_catalogo_riel_simple'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='direccion_entrega',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ventanacotizada',
            name='tipo',
            field=models.CharField(choices=[('Linea20simple', 'Corredera Linea 20 Riel Simple'), ('Linea20lluvia', 'Corredera Linea 20 Riel Lluvia'), ('Linea25simple', 'Corredera Linea 25 Riel Simple'), ('Linea25lluvia', 'Corredera Linea 25 Riel Lluvia'), ('Linea42f', 'Fijo (Linea 42)'), ('Linea42p', 'Proyeccion (Linea 42)')], max_length=20),
        ),
    ]
