# Generated by Django 6.1 on 2026-10-07 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_cliente_direccion_alter_cliente_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seriealuminio',
            name='peso_total_kg',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Peso del paquete (serie completa) en kg. Se usa como denominador en el calculo de precio de cada perfil.', max_digits=8),
        ),
    ]
